applications:
  - name: hunza-backing-services
  memory: 512M
  instances: 1
  host: hunza-backing-services-host
  domain: cfapps.io
  path: target/hunza.jar
  services:
    - postgresql-db
    - rabbitmq
  env:
    SPRING_PROFILES_ACTIVE: cloud
    DEBUG: "true"
    debug: "true"